### PR TITLE
Add coolops.io to the Slack section

### PR DESCRIPTION
**Pull request by thiagorp**

### CODE REVIEW

**Comment by exAspArk** [comment]
Hey @thiagorp!

Do you still work on the project? There are more and more interesting projects are created. I was thinking maybe it makes sense to create a dedicated section.  For example:

## Contents

* [Articles]()
* [Videos]()
* [Books]()
* [Events]()
* [Podcasts]()
* [Resources]()
* [Services]()
* [Bots]()

....

## Services

* [coolops.io](https://coolops.io/) – free. Integrates with Slack, CircleCI.
* [workflowci.com](https://www.workflowci.com/) – freemium. Integrates with Slack, GitHub, CircleCI, Google Cloud Build.

^ I was working on this project as a hobby (Elixir, React, GraphQL, etc.), never posted a link yet :)

P.S. The GitHub link on your website is broken :)

**Comment by thiagorp** [comment]
Hey!

I am still working on the project, yes.

Thanks for notifying about the broken links, I changed the organization name from `coolopsio` to `coolops-io` on Github. I will fix the landing page 😄 

The new section would also sound nice 😄, would you like me to change on the PR?

**Comment by exAspArk** [comment]
> would you like me to change on the PR?

yes, please 🙏

**Comment by exAspArk** [comment]
FYI: I added a new [Services](https://github.com/exAspArk/awesome-chatops#services) section with some [Contribution Guidelines](https://github.com/exAspArk/awesome-chatops/blob/master/CONTRIBUTING.md).

**Pull request closed without merging**
