### PR TITLE
Add Cog bot in HipChat & Slack

### PR DESCRIPTION
**Pull request by agis**
Closes https://github.com/operable/cog/issues/936

### CODE REVIEW

**Comment by exAspArk** [comment]
@agis- thank you! Didn't know about `cog` :)

Can we also [specify](https://github.com/exAspArk/awesome-chatops/blob/master/CONTRIBUTING.md#for-bots-section) something like "Any language" as a `Programming language` and "Docker" as a `Platform`?

**Comment by agis** [comment]
@exAspArk You're welcome! Docker is optional though, how should we make it apparent? Maybe (Any, Elixir)?

**Comment by exAspArk** [comment]
@agis- thanks for clarifying about Docker.

I haven't thought about specifying the language in which the tool is written. Maybe because in some cases it is not so important for me to choose the tool depending on this factor. 

For example, I use `elasticsearch` which is written in Java. I don't write Java code. But knowing that it runs on top of JVM is more important for me when it necessary to customize default settings or tune performance.

That is why I would choose something like `Cog (Any language, Erlang VM)` or just `Cog (Any language)`. What do you think?

**Comment by agis** [comment]
I agree, that's why I think `Platform` is not so well-defined: if I use Docker to deploy, is the platform Docker or Erlang VM?

I'd go with `Cog (Any language)`.

**Comment by exAspArk** [comment]
Yep 👍 
Just one last thing, could you please squash your commits into one and I'll merge it.

**Comment by agis** [comment]
@exAspArk done!

**Comment by exAspArk** [comment]
Thanks a lot for sharing!

**Pull request merged**
